config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get 'articles', to: 'pages#articles'
  get 'contact', to: 'pages#contact'
  get 'madwork', to: 'pages#madwork'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def articles
  end

  def contact
  end

  def madwork
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css">    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= render 'shared/footer' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/articles.html.erb
<div class="articles-container animated fadeIn">
  <div class="description">
    <h5>Behind the keyboard.</h5>
  </div>
  <div class="articles">
    <a class="card hvr-grow" id="watir-article" href="https://medium.com/@franciscoantunesbarreto1997/configuring-watir-with-ruby-on-rails-for-heroku-e96433854430" target="_blank">
    </a>
    <a class="card hvr-grow" id="localhost-article" href="https://medium.com/@franciscoantunesbarreto1997/accessing-localhost-from-your-phone-on-your-rails-app-96aaa91e29c4" target="_blank">
    </a>
  </div>
</div>

app/views/pages/contact.html.erb
<div class="contact-container animated fadeIn">
  <div class="contact-row">
    <div class="left">
      <h5>I'm a Ruby on Rails developer with 2+ years of experience, I'm currently teaching RoR at Le Wagon in <a href="https://www.lewagon.com/lisbon" target="_blank">Lisbon</a> and Le Wagon in <a href="https://www.lewagon.com/munich" target="_blank">Munich</a> while working as a freelancer, in my spare time I also like to build things.</h5>
    </div>
    <div class="right">
      <p>Contact</p>
      <br>
      <p>franciscoantunesbarreto1997@gmail.com</p>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="projects-container animated fadeIn">
  <a class="card madwork hvr-grow" href="/madwork">
  </a>
  <a class="card hvr-grow">
  </a>
  <a class="card hvr-grow">
  </a>
  <a class="card hvr-grow">
  </a>
  <a class="card hvr-grow">
  </a>
  <a class="card hvr-grow">
  </a>
</div>

app/views/pages/madwork.html.erb
<div class="project-container animated fadeIn">
  <div class="description">
    <h5><strong>MADWORK</strong> is a scraper that intends to help developers find job opportunities without having to search 50 different websites.
    </h5>
  </div>
  <div class="picture-container">
    <div class="picture" id="madwork-1"></div>
   </div>
  <div class="description">
    <h5>The app was built using Ruby on Rails, ES6, Nokogiri, HTTParty, Watir and Selenium Webdriver.</h5>
  </div>
  <div class="picture-container">
    <div class="picture" id="madwork-2"></div>
   </div>
  <div class="description">
    <h5>Building the app wasn't much of a technical challenge, the "hardest" part was coping with the tedious task of scraping different websites while dealing with the usual issues such as duplicated titles, weirdly formatted dates, IP address blocks and anti-scraping techniques.</h5>
  </div>
  <div class="picture-container">
    <div class="picture" id="madwork-3"></div>
   </div>
  <div class="description">
    <h5>All in all, this project made me learn a ton about building scrapers and the power of Watir and
    Selenium Webdriver, which I naively thought was just a testing tool, but turns out to be a powerful tool that can be used for various other things like dynamic scraping and browser automation.</h5>
  </div>
  <div class="description">
    <%= link_to "Visit", "http://madwork.co/", target: :_blank, class: "hvr-float-shadow" %>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <h4>Made with <i class="fas fa-beer"></i> by me</h4>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar">
  <div class="name">
    <h2><strong>Francisco Barreto</strong></h2>
  </div>
  <div class="navigation-items">
    <%= link_to "Projects", root_path %>
    <%= link_to "Articles", articles_path %>
    <%= link_to "Contact", contact_path %>
    <%= link_to "https://github.com/franciscobarreto1997", target: :_blank do %>
      <i class="fab fa-github"></i>
    <% end %>
  </div>
  <div class="burguer-menu" hidden>
    <div class="lines"></div>
  </div>
</div>
<div class="mobile-menu opacity" hidden>

</div>